# Generated by Django 5.2.7 on 2025-11-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono CSS (ej: fa-film)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Streaming',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_por_peso', models.IntegerField(default=10, help_text='Puntos necesarios por cada peso COP')),
                ('puntos_minimos_canje', models.IntegerField(default=500, help_text='Mínimo de puntos para canjear')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Configuración de Recompensas',
            },
        ),
        migrations.CreateModel(
            name='ServicioStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo del servicio')),
                ('descripcion', models.TextField()),
                ('sitio_web', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core_public.categoriastreaming')),
            ],
            options={
                'verbose_name_plural': 'Servicios de Streaming',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Básico, Premium, Familiar', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('caracteristicas', models.JSONField(default=list, help_text='Lista de características del plan')),
                ('puntos_primera_compra', models.IntegerField(default=100, help_text='Puntos por primera compra')),
                ('puntos_renovacion', models.IntegerField(default=50, help_text='Puntos por cada renovación')),
                ('activo', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='core_public.serviciostreaming')),
            ],
            options={
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['servicio', 'precio'],
            },
        ),
    ]
