# Generated by Django 5.2.7 on 2025-11-08 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoVerificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(help_text='Correo electrónico verificado', max_length=254)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para verificación')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales')),
                ('agregado_por', models.ForeignKey(blank=True, help_text='Administrador que agregó este correo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(help_text='Servicio de streaming al que pertenece este correo', on_delete=django.db.models.deletion.CASCADE, related_name='correos_verificados', to='core_public.serviciostreaming')),
            ],
            options={
                'verbose_name': 'Correo Verificado',
                'verbose_name_plural': 'Correos Verificados',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('correo', 'servicio')},
            },
        ),
    ]
