# Generated by Django 5.2.7 on 2025-11-06 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('puntos_totales', models.IntegerField(default=0, help_text='Total de puntos acumulados históricamente')),
                ('puntos_disponibles', models.IntegerField(default=0, help_text='Puntos disponibles para canjear')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de validación'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('validada', models.BooleanField(default=False, help_text='¿La compra ha sido validada por un admin?')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('pse', 'PSE'), ('efectivo', 'Efectivo'), ('puntos', 'Canje de puntos')], max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_otorgados', models.IntegerField(default=0, help_text='Puntos de cashback otorgados')),
                ('es_primera_compra', models.BooleanField(default=False)),
                ('email_servicio', models.EmailField(help_text='Email usado en el servicio de streaming', max_length=254)),
                ('notas', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_public.plansuscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganado', 'Puntos ganados'), ('canjeado', 'Puntos canjeados')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core_user.perfilusuario')),
            ],
            options={
                'verbose_name_plural': 'Transacciones de Puntos',
                'ordering': ['-fecha'],
            },
        ),
    ]
