# Generated by Django 5.2.7 on 2025-11-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del comprador', max_length=200)),
                ('telefono', models.CharField(help_text='Teléfono de contacto', max_length=15)),
                ('direccion', models.TextField(help_text='Dirección de facturación')),
                ('correo', models.EmailField(help_text='Correo electrónico para confirmación', max_length=254)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('pse', 'PSE'), ('efectivo', 'Efectivo'), ('puntos', 'Puntos'), ('mixto', 'Mixto (Puntos + Otro método)')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total de la compra', max_digits=10)),
                ('puntos_usados', models.IntegerField(default=0, help_text='Puntos utilizados en el pago')),
                ('valor_puntos', models.DecimalField(decimal_places=2, default=0, help_text='Valor en pesos de los puntos usados', max_digits=10)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, default=0, help_text='Monto restante a pagar por otro método', max_digits=10)),
                ('metodo_pago_secundario', models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('pse', 'PSE'), ('efectivo', 'Efectivo'), ('puntos', 'Puntos'), ('mixto', 'Mixto (Puntos + Otro método)')], help_text='Método de pago para el monto restante (pago mixto)', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False, help_text='Si el pago ha sido confirmado')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, unique=True)),
                ('suscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core_user.suscripcion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
