# Generated by Django 5.2.7 on 2025-11-08 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_public', '0001_initial'),
        ('core_user', '0002_factura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='usuario_servicio',
            field=models.CharField(blank=True, help_text='Nombre de usuario en el servicio (Netflix, Spotify, etc.)', max_length=200),
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo', max_length=200)),
                ('correo', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('nombre_usuario_app', models.CharField(help_text='Nombre de usuario en la app del servicio (Netflix, Spotify, etc.)', max_length=200)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto pagado por la compra', max_digits=10)),
                ('fecha_compra', models.DateField(help_text='Fecha en que realizó la compra')),
                ('comprobante', models.FileField(blank=True, help_text='Captura de pantalla o comprobante de pago (opcional)', null=True, upload_to='comprobantes/')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre la compra')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('puntos_otorgados', models.IntegerField(default=0, help_text='Puntos otorgados al aprobar')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas del administrador')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan específico (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_compra', to='core_public.plansuscripcion')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Admin que revisó la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_revisadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(help_text='Servicio de streaming adquirido', on_delete=django.db.models.deletion.CASCADE, related_name='registros_compra', to='core_public.serviciostreaming')),
                ('usuario', models.ForeignKey(help_text='Usuario que registra la compra', on_delete=django.db.models.deletion.CASCADE, related_name='registros_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registros de Compras',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
