# Generated by Django 5.2.7 on 2025-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_suscripcion_usuario_servicio_registrocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocompra',
            name='es_primera_compra',
            field=models.BooleanField(default=False, help_text='Si es la primera compra del usuario en este servicio'),
        ),
        migrations.AddField(
            model_name='registrocompra',
            name='puntos_sugeridos',
            field=models.IntegerField(default=0, help_text='Puntos calculados automáticamente según el plan'),
        ),
    ]
