# Generated by Django 5.2.7 on 2025-11-11 20:32

import core_user.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_public', '0001_initial'),
        ('core_user', '0004_registrocompra_es_primera_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocompra',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de pago en formato PDF o imagen (JPG, PNG). Máximo 5MB', null=True, upload_to='comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Solo se permiten archivos PDF, JPG, JPEG, PNG o WEBP'), core_user.models.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='registrocompra',
            index=models.Index(fields=['usuario', 'estado'], name='core_user_r_usuario_f83967_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocompra',
            index=models.Index(fields=['estado', '-fecha_registro'], name='core_user_r_estado_606309_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocompra',
            index=models.Index(fields=['servicio', 'usuario'], name='core_user_r_servici_78a404_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocompra',
            index=models.Index(fields=['-fecha_registro'], name='core_user_r_fecha_r_655e32_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['usuario', 'estado'], name='core_user_s_usuario_eb7f73_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['fecha_vencimiento'], name='core_user_s_fecha_v_12b7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['-fecha_creacion'], name='core_user_s_fecha_c_f683ad_idx'),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['validada', 'estado'], name='core_user_s_validad_94c776_idx'),
        ),
    ]
