# Generated by Django 5.2.7 on 2025-11-11 22:30

import core_user.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_alter_registrocompra_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocompra',
            name='comprobante',
            field=models.FileField(blank=True, help_text='Comprobante de pago en formato PDF o imagen (JPG, PNG). Máximo 5MB', null=True, upload_to='comprobantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'], message='Solo se permiten archivos PDF, JPG, JPEG, PNG o WEBP'), core_user.models.validate_file_size_and_content]),
        ),
    ]
